import csv

problem = 'fl'

def train():
    right = []
    wrong = []
    with open(f'./{problem}_right_training.txt') as infile:
        right = infile.readlines()
    with open(f'./{problem}_wrong_training.txt') as infile:
        wrong = infile.readlines()

    # TODO: use training data to calculate and return some bigram probabilities

    # add start and end tokens to each line - This section generated by GitHub Copilot
    right = ['<s> ' + line.strip() + ' </s>' for line in right]
    wrong = ['<s> ' + line.strip() + ' </s>' for line in wrong]

    rightProbabilities = []
    wrongProbabilities = []

    # compute bigrams for right answers - This section partially generated by GitHub Copilot and modified by me
    for line in right:
        words = line.split()
        for i in range(1, len(words) - 1):
            
            rightProbabilities.append((words[i - 1], words[i]))
    
    # compute bigrams for wrong answers - This section partially generated by GitHub Copilot and modified by me
    for line in wrong:
        words = line.split()
        for i in range(1, len(words) - 1):
            wrongProbabilities.append((words[i - 1], words[i]))





def test(bigrams_right, bigrams_wrong):
    correctly_graded = 0
    incorrectly_graded = 0

    submissions = {}
    with open(f'./{problem}_test_data.csv', newline='') as csvfile:
        reader = csv.reader(csvfile, delimiter=',')
        for row in reader:
            submissions[row[1]] = row[2]
    del submissions['Student.answer']

    # TODO Use your bigrams to grade each student input and check if you graded
    # it correctly

    print("Number graded correctly: ", correctly_graded)
    print("Number graded incorrectly: ", incorrectly_graded)


if __name__ == '__main__':

    bigrams_right, bigrams_wrong = train()
    test(bigrams_right, bigrams_wrong)
